import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import SignInNavbar from "@/components/navbar/SignInNavbar";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <SignInNavbar />
        {children}
      </body>
    </html>
  );
}
